
import com.toedter.calendar.DateUtil;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.ExecutionException;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import org.openide.util.Exceptions;
import java.util.GregorianCalendar;
import java.util.TimeZone;
import jxl.write.DateTime;
import org.apache.tools.ant.util.DateUtils;
import org.apache.xmlbeans.impl.tool.Diff;
import org.joda.time.Days;
import org.joda.time.LocalDate;
import org.joda.time.Months;
import org.joda.time.Period;
import org.joda.time.PeriodType;
import java.util.Calendar;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frm_maintenance.java
 *
 * Created on Feb 16, 2016, 4:59:22 PM
 */

/**
 *
 * @author my
 */
public class frm_receive extends javax.swing.JFrame {
functionss s=new functionss();
String qry;

int mt;
//Date date;
    /** Creates new form frm_maintenance */
    public frm_receive() {
        initComponents();
         this.pack();
         this.setLocationRelativeTo(null);

        this.setTitle("Property Mangement System");
        try {

            
            ttoday.setDate(new Date());
            
            cmbpno.removeAllItems();
            cmbrno.removeAllItems();
            qry="select * from property ";
            s.Run(qry, "Read");
            while(s.rs.next())
            {
                cmbpno.addItem(String.valueOf(s.rs.getInt(1)));
            }
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        cmbpno = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbrno = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        tlast = new com.toedter.calendar.JDateChooser();
        submit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ttoday = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        fine = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cno = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        btnreceive = new javax.swing.JButton();
        amt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox();
        Invoice = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        dayDiff = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        due = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tnext = new com.toedter.calendar.JDateChooser();
        btnview = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24));
        jLabel1.setText("Receive Payments...");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Plot No");

        cmbpno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbpno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbpnoFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Room No");

        cmbrno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Receive for");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Last Payment");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Amount");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Given By");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Description");

        submit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Today's Date");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Fine Amount");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Total Amount");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Cno");

        jSeparator2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Select plot no...");

        btnreceive.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnreceive.setText("Receive");
        btnreceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreceiveActionPerformed(evt);
            }
        });

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "maintenance", "rent" }));

        Invoice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Invoice.setText("Invoice");
        Invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvoiceActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Day Difference");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Previous due");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Next Payment");

        btnview.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnview.setText("View");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(10, 10, 10)
                                    .addComponent(ttoday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(cno, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(cname, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                            .addGap(5, 5, 5))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(tlast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(tnext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbrno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbpno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(14, 14, 14)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jLabel10)))
                                        .addGap(10, 10, 10))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(due, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(amt, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(fine, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                                .addGap(97, 97, 97))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(btnreceive)
                                .addGap(18, 18, 18)
                                .addComponent(Invoice))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(29, 29, 29)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(submit))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(btnview)))))
                .addContainerGap())
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayDiff, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(380, 380, 380))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbpno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submit)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbrno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(cno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(tlast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tnext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ttoday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(due, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnreceive, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Invoice))
                        .addGap(18, 18, 18)
                        .addComponent(btnview))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(dayDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbpnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbpnoFocusLost
        
         try {
            String ssq="Yes";
            cmbrno.removeAllItems();
             String qry="select * from rooms where Bno='"+cmbpno.getSelectedItem()+"' ";
            s.Run(qry, "Read");
            if(s.rs.first())
            {
                String qry1="select * from rooms where Bno='"+cmbpno.getSelectedItem()+"' ";
            s.Run(qry1, "Read");

                while(s.rs.next())
                {
                    cmbrno.addItem(String.valueOf(s.rs.getInt(1)));
                 }
            }
            else
            {
                 cmbrno.addItem("0");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbpnoFocusLost

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
       dayDiff.setText("0");
       amt.setText("0");
       fine.setText("0");
       due.setText("0");
        try {

            if(cmbrno.getSelectedItem().equals(0) || cmbrno.getSelectedItem()=="")
            {
              s.Run("select * from customer where bno="+cmbpno.getSelectedItem()+" and rno=0", "Read");
              if(s.rs.next())
              {
                  cno.setText(String.valueOf(s.rs.getInt(1)));
                      cname.setText(s.rs.getString(2));
                      tlast.setDate(s.rs.getDate(10));

              }
              else
              {
                  JOptionPane.showMessageDialog(null, "this property not owned by anyone!");
                  return;
              }

            }
            else
            {
                s.Run("select * from customer where bno="+cmbpno.getSelectedItem()+" and rno="+cmbrno.getSelectedItem()+"", "Read");
                if(s.rs.next())
                {
                    cno.setText(String.valueOf(s.rs.getInt(1)));
                      cname.setText(s.rs.getString(2));
                      tlast.setDate(s.rs.getDate(10));

                      //due.setText(Diff());
                }
                else
              {
                  JOptionPane.showMessageDialog(null, "this property not owned by anyone!");
                  return;
              }
            }


 if(jComboBox1.getSelectedItem().equals("rent") )
   {

          s.Run("select * from property where id="+cmbpno.getSelectedItem()+"", "Read");
          if(s.rs.next())
           {
              if(!s.rs.getString(2).equals("Building"))
              {
              desc.setText(s.rs.getString(7));
              amt.setText(String.valueOf(s.rs.getInt(8)));
              }
          }
           s.Run("select * from rooms where RoomNo="+cmbrno.getSelectedItem()+" and Bno="+cmbpno.getSelectedItem()+"", "Read");
          if(s.rs.next())
           {

              desc.setText(s.rs.getString(6));
              amt.setText(String.valueOf(s.rs.getInt(7)));

          }

    }
 else
 {
                desc.setText("Maintenance for water bill, security, common area light bill etc..");
                mt=Integer.valueOf(JOptionPane.showInputDialog("Enter maintenance amount"));
                amt.setText(""+mt);

 }
  s.Run("select * from income where  pno="+cmbpno.getSelectedItem()+" and rno="+cmbrno.getSelectedItem()+" and type='"+jComboBox1.getSelectedItem()+"'","Read");
            if(s.rs.next())
            {
                tlast.setDate(s.rs.getDate(7));
                tnext.setDate(s.rs.getDate(8));
                if(ttoday.getDate().getTime()<tnext.getDate().getTime())
            {
                JOptionPane.showMessageDialog(null,"Your payment is already paid!");
                return;

            }
            }
            else
            {
                Date tl=tlast.getDate();
               tl.setMonth(tl.getMonth()+1);
            tnext.setDate(tl);
            }

// Date l=tlast.getDate() ;
//        Date p=ttoday.getDate();
//
//        l.setMonth(l.getMonth()+1);
//        String xdate;
//        tnext.setDate(l);
        long diff=ttoday.getDate().getTime()-tnext.getDate().getTime();
        dayDiff.setText(""+(diff/(1000*60*60*24)));
        int dd=Integer.parseInt(dayDiff.getText());


        if(dd>30)
        {
            fine.setText("300");
          int ddue=dd/30;
          int f=Integer.parseInt(amt.getText())*ddue;
          due.setText(""+(f-(Integer.parseInt(amt.getText()))));
        }


         Date l1=ttoday.getDate() ;

        tlast.setDate(ttoday.getDate());
        l1.setMonth(l1.getMonth()+1);
        tnext.setDate(l1);


        int tamt=Integer.parseInt(amt.getText())+Integer.parseInt(fine.getText())+Integer.parseInt(due.getText());
        total.setText(""+tamt);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);



        }
//
//
//        // TODO add your handling code here:
}//GEN-LAST:event_submitActionPerformed

    private void btnreceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreceiveActionPerformed
        try {
            int f=0;
             s.Run("select * from income where  pno="+cmbpno.getSelectedItem()+" and rno="+cmbrno.getSelectedItem()+" and type='"+jComboBox1.getSelectedItem()+"'","Read");
            if(s.rs.next())
            {
                f=1;
                if(ttoday.getDate().getTime()<s.rs.getDate(8).getTime())
                    {
                JOptionPane.showMessageDialog(null,"Your payment is already paid!");
                return;

                      }
            }

             SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String d1 = sdf.format(tnext.getDate());
            String d2=sdf.format(tlast.getDate());
            if(f==0)
            {

             qry="Insert into income values(default,"+cmbpno.getSelectedItem()+","+cmbrno.getSelectedItem()+",'"+jComboBox1.getSelectedItem()+"',"+cno.getText()+","+amt.getText()+",'"+d2+"','"+d1+"',"+fine.getText()+","+due.getText()+","+total.getText()+")";
             s.Run(qry, "Write");
             JOptionPane.showMessageDialog(null,"Received payment!");
            }
            else
            {
             qry="Update income set cno="+cno.getText()+",amount="+amt.getText()+",lastdate='"+d2+"'," +"nextdate='"+d1+"',fine="+fine.getText()+"," +"due="+due.getText()+",total="+total.getText()+" where pno="+cmbpno.getSelectedItem()+" and rno="+cmbrno.getSelectedItem()+" and type='"+jComboBox1.getSelectedItem()+"'";
            s.Run(qry, "Write");
            JOptionPane.showMessageDialog(null,"Received payment!");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }



}//GEN-LAST:event_btnreceiveActionPerformed


    private void InvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvoiceActionPerformed
// String sql="SELECT income.`id` AS income_id, income.`pno` AS income_pno, income.`rno` AS income_rno,income.`cno` AS income_cno,income.`amount` AS income_amount,income.`lastdate` AS income_lastdate,income.`nextdate` AS income_nextdate,income.`fine` AS income_fine,income.`due` AS income_due, income.`total` AS income_total,customer.`id` AS customer_id,customer.`name` AS customer_name,customer.`phno` AS customer_phno,customer.`emailid` AS customer_emailid,customer.`address` AS customer_address,customer.`image` AS customer_image, customer.`bno` AS customer_bno,customer.`rno` AS customer_rno,customer.`proof` AS customer_proof, customer.`doj` AS customer_doj, property.`id` AS property_id,property.`type` AS property_type property.`location` AS property_location property.`price` AS property_price,property.`available` AS property_available, property.`address` AS property_address, property.`description` AS property_description,property.`rent` AS property_rent,rooms.`RoomNo` AS rooms_RoomNo,rooms.`Bno` AS rooms_Bno, rooms.`wng` AS rooms_wng  rooms.`Floor` AS rooms_Floor, rooms.`Price` AS rooms_Price, rooms.`Description` AS rooms_Description, rooms.`Rent` AS rooms_Rent, rooms.`Available` AS rooms_Available,income.`type` AS income_typ FROM `customer` customer INNER JOIN `income` income ON customer.`id` = income.`cno`   INNER JOIN `property` property ON income.`pno` = property.`id` INNER JOIN `rooms` rooms ON income.`rno` = rooms.`RoomNo`";

        try {
            int st=0;
           s.Run("select * from income where  pno="+cmbpno.getSelectedItem()+" and rno="+cmbrno.getSelectedItem()+" and type='"+jComboBox1.getSelectedItem()+"'","Read");
            if(s.rs.next())
            {
               st=s.rs.getInt(1);
            }

           // String sql="SELECT  income.`id` AS income_id,   income.`pno` AS income_pno,  income.`rno` AS income_rno,   income.`cno` AS income_cno,    income.`amount` AS income_amount,   income.`lastdate` AS income_lastdate,     income.`nextdate` AS income_nextdate,     income.`fine` AS income_fine,   income.`due` AS income_due,    income.`total` AS income_total,     customer.`id` AS customer_id,     customer.`name` AS customer_name,    customer.`phno` AS customer_phno,   customer.`emailid` AS customer_emailid,  customer.`address` AS customer_address,   customer.`image` AS customer_image,  customer.`bno` AS customer_bno,  customer.`rno` AS customer_rno, customer.`proof` AS customer_proof,    customer.`doj` AS customer_doj, property.`id` AS property_id, property.`type` AS property_type, property.`location` AS property_location, property.`price` AS property_price,  property.`available` AS property_available,  property.`address` AS property_address,   property.`description` AS property_description,  property.`rent` AS property_rent,  rooms.`RoomNo` AS rooms_RoomNo,   rooms.`Bno` AS rooms_Bno,  rooms.`wng` AS rooms_wng,  rooms.`Floor` AS rooms_Floor,  rooms.`Price` AS rooms_Price,  rooms.`Description` AS rooms_Description,  rooms.`Rent` AS rooms_Rent,  rooms.`Available` AS rooms_Available, income.`type` AS income_type FROM    `customer` customer INNER JOIN `income` income ON customer.`id` = income.`cno`   INNER JOIN `property` property ON income.`pno` = property.`id`    INNER JOIN `rooms` rooms ON income.`rno` = rooms.`RoomNo` where id="+st+"";
            String sql="SELECT  income.`id` AS income_id,   income.`pno` AS income_pno,  income.`rno` AS income_rno,   income.`cno` AS income_cno,    income.`amount` AS income_amount,   income.`lastdate` AS income_lastdate,     income.`nextdate` AS income_nextdate,     income.`fine` AS income_fine,   income.`due` AS income_due,    income.`total` AS income_total,     customer.`id` AS customer_id,     customer.`name` AS customer_name,    customer.`phno` AS customer_phno,   customer.`emailid` AS customer_emailid,  customer.`address` AS customer_address,   customer.`image` AS customer_image,  customer.`bno` AS customer_bno,  customer.`rno` AS customer_rno, customer.`proof` AS customer_proof,    customer.`doj` AS customer_doj, property.`id` AS property_id, property.`type` AS property_type, property.`location` AS property_location, property.`price` AS property_price,  property.`available` AS property_available,  property.`address` AS property_address,   property.`description` AS property_description,  property.`rent` AS property_rent,  rooms.`RoomNo` AS rooms_RoomNo,   rooms.`Bno` AS rooms_Bno,  rooms.`wng` AS rooms_wng,  rooms.`Floor` AS rooms_Floor,  rooms.`Price` AS rooms_Price,  rooms.`Description` AS rooms_Description,  rooms.`Rent` AS rooms_Rent,  rooms.`Available` AS rooms_Available, income.`type` AS income_type FROM    `customer` customer INNER JOIN `income` income ON customer.`id` = income.`cno`   INNER JOIN `property` property ON income.`pno` = property.`id`    INNER JOIN `rooms` rooms ON income.`rno` = rooms.`RoomNo` where income.`id`="+st+"";
           s.SetReport("\\bbiill.jrxml", sql);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
    }//GEN-LAST:event_InvoiceActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
new rptfrm().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_receive().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Invoice;
    private javax.swing.JTextField amt;
    private javax.swing.JButton btnreceive;
    private javax.swing.JButton btnview;
    private javax.swing.JComboBox cmbpno;
    private javax.swing.JComboBox cmbrno;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cno;
    private javax.swing.JTextField dayDiff;
    private javax.swing.JTextArea desc;
    private javax.swing.JTextField due;
    private javax.swing.JTextField fine;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton submit;
    private com.toedter.calendar.JDateChooser tlast;
    private com.toedter.calendar.JDateChooser tnext;
    private javax.swing.JTextField total;
    private com.toedter.calendar.JDateChooser ttoday;
    // End of variables declaration//GEN-END:variables

}
