
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frm_property.java
 *
 * Created on Jan 14, 2016, 11:05:50 PM
 */

/**
 *
 * @author my
 */
public class frm_property extends javax.swing.JFrame {
     DefaultTableModel model;
functionss s=new functionss();

    /** Creates new form frm_property */
    public frm_property() throws SQLException {
        initComponents();
         this.pack();
         this.setLocationRelativeTo(null);

        this.setTitle("Property Details");
        String qry="";
        locationcmb.removeAllItems();
        typecmb.removeAllItems();
                 model=(DefaultTableModel)jTable2.getModel();
        qry="select * from location";
        s.Run(qry, "Read");
        while(s.rs.next())
        {
             locationcmb.addItem(s.rs.getString(2));

        }
        s.pst.close();
        s.con.close();
        qry="select * from type";
        s.Run(qry, "Read");
        while(s.rs.next())
        {
             typecmb.addItem(s.rs.getString(2));

        }
                    model.setRowCount(0);
            qry="select * from property";
    s.Run(qry,"Read");
    while(s.rs.next())
    {
        String s1[]={String.valueOf(s.rs.getInt(1)),s.rs.getString(2),s.rs.getString(3),s.rs.getString(4),s.rs.getString(5),s.rs.getString(6),s.rs.getString(7)};
model.addRow(s1);


    }
        s.pst.close();
       s.con.close();
        
    }
    


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        typecmb = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        locationcmb = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addresstxt = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        pricetxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        desctxt = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        insertbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        viewbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        rent = new javax.swing.JTextField();
        btnclear = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24));
        jLabel1.setText("Enter property details...");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("ID");

        idtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idtxtKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Type");

        typecmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Location");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Address");

        addresstxt.setColumns(20);
        addresstxt.setRows(5);
        addresstxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addresstxtKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(addresstxt);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Price");

        pricetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pricetxtKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Available");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Description");

        desctxt.setColumns(20);
        desctxt.setRows(5);
        desctxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                desctxtKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(desctxt);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Yes");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("No");

        jSeparator1.setForeground(new java.awt.Color(0, 153, 153));

        jSeparator2.setBackground(new java.awt.Color(0, 153, 153));

        insertbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        insertbtn.setText("Insert");
        insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbtnActionPerformed(evt);
            }
        });

        updatebtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        viewbtn.setFont(new java.awt.Font("Tahoma", 1, 11));
        viewbtn.setText("View");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Rent");

        rent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rentKeyTyped(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnclear.setText("clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rent)
                            .addComponent(pricetxt)
                            .addComponent(locationcmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(typecmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(32, 32, 32)
                                        .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnclear))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(insertbtn)
                .addGap(27, 27, 27)
                .addComponent(updatebtn)
                .addGap(18, 18, 18)
                .addComponent(viewbtn)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(typecmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(locationcmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnclear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertbtn)
                    .addComponent(updatebtn)
                    .addComponent(viewbtn))
                .addGap(30, 30, 30))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "type", "location", "price", "available", "address", "description"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable2KeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbtnActionPerformed
        String rb="";
       // DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        try {
            if(idtxt.getText().length()==0||pricetxt.getText().length()==0||addresstxt.getText().length()==0||desctxt.getText().length()==0||rent.getText().length()==0)
            {
                JOptionPane.showMessageDialog(null,"Fill all the details!");
                return;
            }
            if(jRadioButton1.isSelected())
                 rb=jRadioButton1.getText();
            else
                rb=jRadioButton2.getText();
            String t=String.valueOf(typecmb.getSelectedItem());
            String l=String.valueOf(locationcmb.getSelectedItem());
            if(idtxt.getText().equals("default"))
            {

            }
            else
            {
            String q="select * from property where id="+idtxt.getText()+"";
            s.Run(q,"Read");
            if(s.rs.next())
            {
                JOptionPane.showMessageDialog(null, "This id already exist!");
                return;
            }
            }

           String qry="insert into property values("+idtxt.getText()+",'"+t+"','"+l+"','"+pricetxt.getText()+"','"+rb+"','"+addresstxt.getText()+"','"+desctxt.getText()+"',"+rent.getText()+")";
           
        s.Run(qry, "Write");
        JOptionPane.showMessageDialog(null, "inserted successfully!");

       

                    model.setRowCount(0);
           qry="select * from property";
    s.Run(qry,"Read");
    while(s.rs.next())
    {
        String s1[]={String.valueOf(s.rs.getInt(1)),s.rs.getString(2),s.rs.getString(3),s.rs.getString(4),s.rs.getString(5),s.rs.getString(6),s.rs.getString(7),String.valueOf(s.rs.getInt(8))};
model.addRow(s1);

    }
        if (t.equalsIgnoreCase("Building")){
            NewClass.tmpval=idtxt.getText();
            new frm_roomdetails().setVisible(true);
        }

        s.pst.close();
       s.con.close();


        model.setRowCount(0);
            qry="select * from property";
    s.Run(qry,"Read");
    while(s.rs.next())
    {
        String s1[]={String.valueOf(s.rs.getInt(1)),s.rs.getString(2),s.rs.getString(3),s.rs.getString(4),s.rs.getString(5),s.rs.getString(6),s.rs.getString(7),String.valueOf(s.rs.getInt(8))};
model.addRow(s1);
    }
   s.pst.close();
      s.con.close();

         

     


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_insertbtnActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed

        try {
           int st=Integer.parseInt(JOptionPane.showInputDialog("Enter a property id"));
               String qry="select * from property where id =" +st+ "";
           s.Run(qry,"Read");


            if(s.rs.next())
            {
               idtxt.setText(String.valueOf(s.rs.getInt(1)));
               typecmb.setSelectedItem(s.rs.getString(2));
               locationcmb.setSelectedItem(s.rs.getString(3));
               pricetxt.setText(s.rs.getString(4));
               if(s.rs.getString(5).equalsIgnoreCase(jRadioButton1.getText()))
               {
                   jRadioButton1.setSelected(true);
               }
                   else
                   {
                     jRadioButton2.setSelected(true);
                   }
               addresstxt.setText(s.rs.getString(6));
               desctxt.setText(s.rs.getString(7));
               rent.setText(String.valueOf(s.rs.getInt(8)));
            }
        s.pst.close();
        s.con.close();}
    catch (Exception e) {

         JOptionPane.showMessageDialog(null,e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_viewbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        try {
             if(idtxt.getText().length()==0||pricetxt.getText().length()==0||addresstxt.getText().length()==0||desctxt.getText().length()==0||rent.getText().length()==0)
            {
                JOptionPane.showMessageDialog(null,"Fill all the details!");
                return;
            }
            String rb;
             if(jRadioButton1.isSelected())
                 rb=jRadioButton1.getText();
            else
                rb=jRadioButton2.getText();
             String t=String.valueOf(typecmb.getSelectedItem());
            String l=String.valueOf(locationcmb.getSelectedItem());
            String qry="Update property set type='"+t+"',location='"+l+"',price='"+pricetxt.getText()+"',available='"+rb+"',address='"+addresstxt.getText()+"',description='"+desctxt.getText()+"',rent="+rent.getText()+" where id="+idtxt.getText()+"";
         s.Run(qry, "Write");
    
        model.setRowCount(0);
            qry="select * from property";
    s.Run(qry,"Read");
    while(s.rs.next())
    {
        String s1[]={String.valueOf(s.rs.getInt(1)),s.rs.getString(2),s.rs.getString(3),s.rs.getString(4),s.rs.getString(5),s.rs.getString(6),s.rs.getString(7),String.valueOf(s.rs.getInt(8))};
model.addRow(s1);


    }
       if(t.equals("Building"))
       {
      int n = JOptionPane.showConfirmDialog(null,"Do you want to update any room detail?" , "",JOptionPane.YES_NO_OPTION);
            if(n == JOptionPane.YES_OPTION)
             {
                  new room().setVisible(true);
              }
       }
       else
       {
        JOptionPane.showMessageDialog(null,"Successfully updated!");
       }

        } catch (Exception e) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_updatebtnActionPerformed

    private void jTable2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2KeyPressed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
int row=jTable2.getSelectedRow();

String table_click=jTable2.getModel().getValueAt(row, 0).toString();
//String sql="select * from jTable1 where id='"+table_click+"'";
        try {
          // s.con=NewClass.NewClass();
           String qry="select * from property where id =" + table_click + "";
           s.Run(qry,"Read");

            
            if(s.rs.next())
            {
               idtxt.setText(String.valueOf(s.rs.getInt(1)));
               typecmb.setSelectedItem(s.rs.getString(2));
               locationcmb.setSelectedItem(s.rs.getString(3));
               pricetxt.setText(s.rs.getString(4));
               if(s.rs.getString(5).equalsIgnoreCase(jRadioButton1.getText()))
               {
                   jRadioButton1.setSelected(true);
               }
                   else
                   {
                     jRadioButton2.setSelected(true);
                   }
               addresstxt.setText(s.rs.getString(6));
               desctxt.setText(s.rs.getString(7));
               rent.setText(String.valueOf(s.rs.getInt(8)));
            }
           s.pst.close();
           s.rs.close();

            // TODO add your handling code here:
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void pricetxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pricetxtKeyTyped
char c=evt.getKeyChar();
if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE))
{
   getToolkit().beep();
   evt.consume();
}

        if(pricetxt.getText().length()==10 )
{
    getToolkit().beep();
    evt.consume();
}        // TODO add your handling code here:
    }//GEN-LAST:event_pricetxtKeyTyped

    private void idtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idtxtKeyTyped
char c=evt.getKeyChar();
if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE))
{
   getToolkit().beep();
   evt.consume();
}

        if(idtxt.getText().length()>10 )
{
    getToolkit().beep();
    evt.consume();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtKeyTyped

    private void addresstxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addresstxtKeyTyped
  if(addresstxt.getText().length()>40 )
{
    getToolkit().beep();
    evt.consume();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_addresstxtKeyTyped

    private void desctxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_desctxtKeyTyped
  if(desctxt.getText().length()>40 )
{
    getToolkit().beep();
    evt.consume();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_desctxtKeyTyped

    private void rentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rentKeyTyped
char c=evt.getKeyChar();
if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE))
{
   getToolkit().beep();
   evt.consume();
}

        if(rent.getText().length()>5 )
{
    getToolkit().beep();
    evt.consume();
}        // TODO add your handling code here:
    }//GEN-LAST:event_rentKeyTyped

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
idtxt.setText("default");
pricetxt.setText("");
rent.setText("");
addresstxt.setText("");
desctxt.setText("");

// TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    // frame.setVisible(true);
                    new frm_property().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frm_property.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addresstxt;
    private javax.swing.JButton btnclear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextArea desctxt;
    public javax.swing.JTextField idtxt;
    private javax.swing.JButton insertbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox locationcmb;
    private javax.swing.JTextField pricetxt;
    private javax.swing.JTextField rent;
    private javax.swing.JComboBox typecmb;
    private javax.swing.JButton updatebtn;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables

}
