
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import java.util.Calendar;
import javax.imageio.ImageIO;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.sf.jasperreports.engine.JRException;
import org.openide.util.Exceptions;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmMdi.java
 *
 * Created on Jan 19, 2016, 11:23:36 PM
 */

/**
 *
 * @author my
 */
public class frmMdi extends javax.swing.JFrame {
    functionss ss=new functionss();;

    /** Creates new form frmMdi */
    public frmMdi() {
        initComponents();
        
        // Timer1.start();
        setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("Property Mangement System");
        makeFrameFullSize(jLabel1);
//            ImageIcon imageIcon = new ImageIcon("G:\\PropertyMS\\help\\my.jpg"); // load the image to a imageIcon
//        java.awt.Image image = imageIcon.getImage(); // transform it
//       java.awt.Image newimg = image.getScaledInstance(250, 1000,  java.awt.Image.SCALE_AREA_AVERAGING); // scale it the smooth way
//        imageIcon = new ImageIcon(newimg);
//        jLabel1.setIcon(imageIcon);
// 

    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
//    Timer Timer1 = new Timer(100, new ActionListener() {
//		public void actionPerformed(ActionEvent evt) {
//
//                        Calendar cl = Calendar.getInstance();
//    //for(;;){
//   jLabel1.setText(String.valueOf(cl.getTime()));
//			//System.out.println(clockTime);
//		    }
//    });
      
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        canvas1 = new java.awt.Canvas();
        canvas2 = new java.awt.Canvas();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuProperty = new javax.swing.JMenu();
        subMnuType = new javax.swing.JMenuItem();
        subMnuLocation = new javax.swing.JMenuItem();
        subMnuReg = new javax.swing.JMenuItem();
        mnuMaster = new javax.swing.JMenu();
        subMnuEmp = new javax.swing.JMenuItem();
        subMnuCust = new javax.swing.JMenuItem();
        subMnuVisitor = new javax.swing.JMenuItem();
        mnuInEx = new javax.swing.JMenu();
        receiveMenu = new javax.swing.JMenuItem();
        payMenu = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();
        empReport = new javax.swing.JMenuItem();
        visitorRpt = new javax.swing.JMenuItem();
        custReport = new javax.swing.JMenuItem();
        propertyRpt = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        aboutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(204, 204, 255));
        desktopPane.setOpaque(false);
        canvas1.setBounds(180, 140, -1, -1);
        desktopPane.add(canvas1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        canvas2.setBounds(210, 130, -1, -1);
        desktopPane.add(canvas2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBounds(1500, 1500, 350, 350);
        desktopPane.add(label1, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBounds(0, 0, 34, 14);
        desktopPane.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        mnuProperty.setText("Property");
        mnuProperty.setName("mnu_property"); // NOI18N

        subMnuType.setText("Type");
        subMnuType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMnuTypeActionPerformed(evt);
            }
        });
        mnuProperty.add(subMnuType);

        subMnuLocation.setText("Location");
        subMnuLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMnuLocationActionPerformed(evt);
            }
        });
        mnuProperty.add(subMnuLocation);

        subMnuReg.setText("Register");
        subMnuReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMnuRegActionPerformed(evt);
            }
        });
        mnuProperty.add(subMnuReg);

        menuBar.add(mnuProperty);

        mnuMaster.setText("Master");

        subMnuEmp.setText("Employee");
        subMnuEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMnuEmpActionPerformed(evt);
            }
        });
        mnuMaster.add(subMnuEmp);

        subMnuCust.setText("Tenant");
        subMnuCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMnuCustActionPerformed(evt);
            }
        });
        mnuMaster.add(subMnuCust);

        subMnuVisitor.setText("Visitor");
        subMnuVisitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMnuVisitorActionPerformed(evt);
            }
        });
        mnuMaster.add(subMnuVisitor);

        menuBar.add(mnuMaster);

        mnuInEx.setText("Income/Expense");

        receiveMenu.setText("Receive ");
        receiveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveMenuActionPerformed(evt);
            }
        });
        mnuInEx.add(receiveMenu);

        payMenu.setText("Pay ");
        payMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payMenuActionPerformed(evt);
            }
        });
        mnuInEx.add(payMenu);

        menuBar.add(mnuInEx);

        mnuReports.setText("Reports");
        mnuReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReportsActionPerformed(evt);
            }
        });

        empReport.setText("Employee");
        empReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empReportActionPerformed(evt);
            }
        });
        mnuReports.add(empReport);

        visitorRpt.setText("Visitor");
        visitorRpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorRptActionPerformed(evt);
            }
        });
        mnuReports.add(visitorRpt);

        custReport.setText("Tenant");
        custReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custReportActionPerformed(evt);
            }
        });
        mnuReports.add(custReport);

        propertyRpt.setText("Property");
        propertyRpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertyRptActionPerformed(evt);
            }
        });
        mnuReports.add(propertyRpt);

        menuBar.add(mnuReports);

        mnuHelp.setText("Help");

        aboutMenu.setText("About..");
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuActionPerformed(evt);
            }
        });
        mnuHelp.add(aboutMenu);

        menuBar.add(mnuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void makeFrameFullSize(JLabel jLabel1) {
       // throw new UnsupportedOperationException("Not yet implemented");
        Dimension screenSize=Toolkit.getDefaultToolkit().getScreenSize();
        jLabel1.setSize(screenSize.width,screenSize.height);
    }

    private void subMnuRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMnuRegActionPerformed
        try {
            new frm_property().setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
      
}//GEN-LAST:event_subMnuRegActionPerformed

    private void subMnuTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMnuTypeActionPerformed
       new frm_type().setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_subMnuTypeActionPerformed

    private void subMnuLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMnuLocationActionPerformed
        new frm_location().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_subMnuLocationActionPerformed

    private void subMnuEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMnuEmpActionPerformed
        new frm_emp().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_subMnuEmpActionPerformed

    private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuActionPerformed
               frmAbout frm=new frmAbout();
                 frm.pack();
               frm.setLocationRelativeTo(null);
              frm.setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_aboutMenuActionPerformed

    private void subMnuVisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMnuVisitorActionPerformed
        new frm_visitor().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_subMnuVisitorActionPerformed

    private void subMnuCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMnuCustActionPerformed
new frm_cust().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_subMnuCustActionPerformed

    private void empReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empReportActionPerformed
String sql="select * from employee ";

            try {
                ss.SetReport("\\report3.jrxml", sql);
            } catch (JRException ex) {
                Exceptions.printStackTrace(ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_empReportActionPerformed

    private void custReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custReportActionPerformed
String sql="select * from customer ";

            try {
                ss.SetReport("\\custReport.jrxml", sql);
            } catch (JRException ex) {
                Exceptions.printStackTrace(ex);
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_custReportActionPerformed

    private void receiveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveMenuActionPerformed
new frm_receive().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_receiveMenuActionPerformed

    private void payMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payMenuActionPerformed
new frm_pay().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_payMenuActionPerformed

    private void mnuReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuReportsActionPerformed

    private void visitorRptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorRptActionPerformed
       String sql="select * from visitor ";

            try {
                ss.SetReport("\\viRpt.jrxml", sql);
            } catch (JRException ex) {
                Exceptions.printStackTrace(ex);
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorRptActionPerformed

    private void propertyRptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertyRptActionPerformed
String sql="select * from property";

            try {
                ss.SetReport("\\propertyRpt.jrxml", sql);
            } catch (JRException ex) {
                Exceptions.printStackTrace(ex);
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_propertyRptActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMdi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenu;
    private java.awt.Canvas canvas1;
    private java.awt.Canvas canvas2;
    private javax.swing.JMenuItem custReport;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem empReport;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuHelp;
    public javax.swing.JMenu mnuInEx;
    public javax.swing.JMenu mnuMaster;
    public javax.swing.JMenu mnuProperty;
    public javax.swing.JMenu mnuReports;
    private javax.swing.JMenuItem payMenu;
    private javax.swing.JMenuItem propertyRpt;
    private javax.swing.JMenuItem receiveMenu;
    public javax.swing.JMenuItem subMnuCust;
    public javax.swing.JMenuItem subMnuEmp;
    private javax.swing.JMenuItem subMnuLocation;
    private javax.swing.JMenuItem subMnuReg;
    public javax.swing.JMenuItem subMnuType;
    public javax.swing.JMenuItem subMnuVisitor;
    private javax.swing.JMenuItem visitorRpt;
    // End of variables declaration//GEN-END:variables

}
