

import java.awt.Rectangle;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.border.Border;






/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * loadfrm.java
 *
 * Created on Mar 10, 2016, 12:13:27 PM
 */

/**
 *
 * @author my
 */
public class loadfrm extends javax.swing.JFrame {

    /** Creates new form loadfrm */
    public loadfrm() {
        initComponents();
        this.setTitle("Property Management System");
        jProgressBar1.setValue(0);
        jProgressBar1.setMinimum(0);
        jProgressBar1.setMaximum(100);
        jProgressBar1.setStringPainted(true);
        Border border=BorderFactory.createTitledBorder("Reading...");
        jProgressBar1.setBorder(border);


        


    }
    public void DoBogusTask(int iCtr)
    {
        Random random=new Random(iCtr);
        for(int ivalue=0;ivalue<random.nextFloat()*1000000;ivalue++)
        {
            System.out.println("ivalue="+ivalue);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(loadfrm.class, "loadfrm.jLabel1.text")); // NOI18N

        jProgressBar1.setBackground(new java.awt.Color(204, 204, 204));
        jProgressBar1.setForeground(new java.awt.Color(0, 102, 102));
        jProgressBar1.setOpaque(true);

        jLabel2.setText(org.openide.util.NbBundle.getMessage(loadfrm.class, "loadfrm.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
int ictr=0;
        for( ictr=1;ictr<101;ictr++)
{
           DoBogusTask(ictr);
    jLabel2.setText("Performing Task "+ictr+" of 100");
    Rectangle labelRect=jLabel2.getBounds();
    labelRect.x=0;
    labelRect.y=0;
    jLabel2.paintImmediately(labelRect);
    jProgressBar1.setValue(ictr);
    Rectangle pRect=jProgressBar1.getBounds();
    pRect.x=0;
    pRect.y=0;
    jProgressBar1.paintImmediately(pRect);

} 
 if(ictr==101)
 {
   // new frm_login().setVisible(true);
     frm_login frame=new frm_login();
                frame.pack();
               frame.setLocationRelativeTo(null);
                frame.setVisible(true);
    this.dispose();
 }
 
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new loadfrm().setVisible(true);
                 loadfrm frame=new loadfrm();
                frame.pack();
               frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

}
