

import java.sql.SQLException;
import java.util.Date;
import javax.print.DocFlavor.STRING;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import org.openide.util.Exceptions;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * rptfrm.java
 *
 * Created on Mar 7, 2016, 6:07:43 PM
 */

/**
 *
 * @author my
 */
public class rptfrm extends javax.swing.JFrame {
   functionss s=new functionss();

  DefaultTableModel model;
    /** Creates new form rptfrm */
    public rptfrm() {
        initComponents();
         this.pack();
         this.setLocationRelativeTo(null);

        this.setTitle("Property Management System");
        try {
            model=(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
             String qry="select * from income";

            s.Run(qry, "Read");
            while(s.rs.next())
            {
                String[] s1={String.valueOf(s.rs.getInt(1)),String.valueOf(s.rs.getInt(2)),String.valueOf(s.rs.getInt(3)),
                s.rs.getString(4),String.valueOf(s.rs.getInt(5)),String.valueOf(s.rs.getInt(6)),
                String.valueOf(s.rs.getDate(7)),String.valueOf(s.rs.getDate(8)),String.valueOf(s.rs.getInt(9)),
                String.valueOf(s.rs.getInt(10)),String.valueOf(s.rs.getInt(11))};
                model.addRow(s1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "pno", "rno", "type", "cno", "amount", "lastdate", "nextdate", "fine", "due", "total"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(rptfrm.class, "rptfrm.jTable1.columnModel.title0")); // NOI18N
        jTable1.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(rptfrm.class, "rptfrm.jTable1.columnModel.title1")); // NOI18N
        jTable1.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(rptfrm.class, "rptfrm.jTable1.columnModel.title2")); // NOI18N
        jTable1.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(rptfrm.class, "rptfrm.jTable1.columnModel.title3")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(rptfrm.class, "rptfrm.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
        try {
            int row=jTable1.getSelectedRow();

String table_click=jTable1.getModel().getValueAt(row, 0).toString();
 String sql="SELECT  income.`id` AS income_id,   income.`pno` AS income_pno,  income.`rno` AS income_rno,   income.`cno` AS income_cno,    income.`amount` AS income_amount,   income.`lastdate` AS income_lastdate,     income.`nextdate` AS income_nextdate,     income.`fine` AS income_fine,   income.`due` AS income_due,    income.`total` AS income_total,     customer.`id` AS customer_id,     customer.`name` AS customer_name,    customer.`phno` AS customer_phno,   customer.`emailid` AS customer_emailid,  customer.`address` AS customer_address,   customer.`image` AS customer_image,  customer.`bno` AS customer_bno,  customer.`rno` AS customer_rno, customer.`proof` AS customer_proof,    customer.`doj` AS customer_doj, property.`id` AS property_id, property.`type` AS property_type, property.`location` AS property_location, property.`price` AS property_price,  property.`available` AS property_available,  property.`address` AS property_address,   property.`description` AS property_description,  property.`rent` AS property_rent,  rooms.`RoomNo` AS rooms_RoomNo,   rooms.`Bno` AS rooms_Bno,  rooms.`wng` AS rooms_wng,  rooms.`Floor` AS rooms_Floor,  rooms.`Price` AS rooms_Price,  rooms.`Description` AS rooms_Description,  rooms.`Rent` AS rooms_Rent,  rooms.`Available` AS rooms_Available, income.`type` AS income_type FROM    `customer` customer INNER JOIN `income` income ON customer.`id` = income.`cno`   INNER JOIN `property` property ON income.`pno` = property.`id`    INNER JOIN `rooms` rooms ON income.`rno` = rooms.`RoomNo` where income.`id`="+table_click+"";
                s.SetReport("\\bbiill.jrxml", sql);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rptfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
